In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
stocks = [
    "RELIANCE.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "SBIN.NS",
    "KOTAKBANK.NS",
    "TCS.NS",
    "INFY.NS",
    "ITC.NS",
    "HINDUNILVR.NS",
    "SUNPHARMA.NS",
    "BHARTIARTL.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "ASIANPAINT.NS",
    "ULTRACEMCO.NS",
    "NTPC.NS",
    "POWERGRID.NS",
    "TATASTEEL.NS",
    "HINDALCO.NS"
]

In [3]:
prices = yf.download(
    stocks,
    start="2015-01-01",
    end="2026-01-01",
    auto_adjust=True
)

[*********************100%***********************]  20 of 20 completed

In [4]:
prices.head()

Price              Close                                                      \
Ticker     ASIANPAINT.NS BHARTIARTL.NS HDFCBANK.NS HINDALCO.NS HINDUNILVR.NS
Date
2015-01-01    679.040222    304.244568  213.700851  145.910370    626.796509
2015-01-02    702.516418    306.047119  216.675003  147.429779    624.730530
2015-01-05    702.471069    299.256287  214.845627  144.436996    628.325317
2015-01-06    685.702454    296.908844  211.501099  141.259979    640.225769
2015-01-07    699.479858    297.621399  212.118408  137.116135    662.704224

Price                                                                     ...  \
Ticker     ICICIBANK.NS     INFY.NS      ITC.NS KOTAKBANK.NS       LT.NS  ...
Date                                                                      ...
2015-01-01   291.565826  359.981110  156.948044   124.743599  840.127502  ...
2015-01-02   299.841888  367.055237  157.439651   126.027107  857.847290  ...
2015-01-05   300.462585  363.901062  158.059479   125.521645  869.781738  ...
2015-01-06   287.717407  356.298096  153.998459   124.025040  840.770508  ...
2015-01-07   279.937958  358.002808  151.134384   126.022171  838.758057  ...

Price        Volume                                                        \
Ticker       M&M.NS MARUTI.NS  NTPC.NS POWERGRID.NS RELIANCE.NS   SBIN.NS
Date
2015-01-01   713338    299232  1478980       778837     2963643   6138488
2015-01-02  1279856    233924  2383093      3612848     7331366   9935094
2015-01-05  1456708    536747  2197057      7291352    10103941   9136716
2015-01-06  2579114    422743  5923512      8288963    18627980  15329257
2015-01-07  2189814    369241  5848555      3256180    20720312  15046745

Price
Ticker     SUNPHARMA.NS TATASTEEL.NS   TCS.NS ULTRACEMCO.NS
Date
2015-01-01       587479     26570816   366830         54097
2015-01-02       710310     36043328   925740        228660
2015-01-05       792287     54638866  1754242        181680
2015-01-06      1709888     64767961  2423784        292468
2015-01-07      1730518     49846923  2636332        120023

[5 rows x 100 columns]

In [5]:
adj_close = prices["Close"].copy()

In [6]:
adj_close.head()

Ticker,ASIANPAINT.NS,BHARTIARTL.NS,HDFCBANK.NS,HINDALCO.NS,HINDUNILVR.NS,ICICIBANK.NS,INFY.NS,ITC.NS,KOTAKBANK.NS,LT.NS,M&M.NS,MARUTI.NS,NTPC.NS,POWERGRID.NS,RELIANCE.NS,SBIN.NS,SUNPHARMA.NS,TATASTEEL.NS,TCS.NS,ULTRACEMCO.NS
Date,,,,,,,,,,,,,,,,,,,,
2015-01-01,679.040222,304.244568,213.700851,145.910370,626.796509,291.565826,359.981110,156.948044,124.743599,840.127502,553.622253,3001.886719,78.782761,47.745945,189.125366,274.925049,750.971252,28.314104,970.330627,2497.059326
2015-01-02,702.516418,306.047119,216.675003,147.429779,624.730530,299.841888,367.055237,157.439651,126.027107,857.847290,548.072815,3018.824707,79.861221,48.320568,188.624847,276.019440,754.670532,28.755150,983.252563,2571.713623
2015-01-05,702.471069,299.256287,214.845627,144.436996,628.325317,300.462585,363.901062,158.059479,125.521645,869.781738,545.298157,3098.078125,79.639999,48.372814,186.558685,273.830597,755.127197,29.171686,968.310242,2576.965332
2015-01-06,685.702454,296.908844,211.501099,141.259979,640.225769,287.717407,356.298096,153.998459,124.025040,840.770508,542.254944,3050.858887,76.985336,47.293224,178.091827,262.579620,738.503845,27.757555,932.612122,2504.656006
2015-01-07,699.479858,297.621399,212.118408,137.116135,662.704224,279.937958,358.002808,151.134384,126.022171,838.758057,547.849121,3089.048096,78.838058,47.972321,181.968475,262.798523,739.645447,27.225506,921.595886,2494.762207

In [7]:
adj_close.shape

(2716, 20)

In [8]:
adj_close.columns.tolist()

['ASIANPAINT.NS',
 'BHARTIARTL.NS',
 'HDFCBANK.NS',
 'HINDALCO.NS',
 'HINDUNILVR.NS',
 'ICICIBANK.NS',
 'INFY.NS',
 'ITC.NS',
 'KOTAKBANK.NS',
 'LT.NS',
 'M&M.NS',
 'MARUTI.NS',
 'NTPC.NS',
 'POWERGRID.NS',
 'RELIANCE.NS',
 'SBIN.NS',
 'SUNPHARMA.NS',
 'TATASTEEL.NS',
 'TCS.NS',
 'ULTRACEMCO.NS']

In [9]:
adj_close.isna().sum()

Ticker
ASIANPAINT.NS    0
BHARTIARTL.NS    0
HDFCBANK.NS      0
HINDALCO.NS      0
HINDUNILVR.NS    0
ICICIBANK.NS     0
INFY.NS          0
ITC.NS           0
KOTAKBANK.NS     0
LT.NS            0
M&M.NS           0
MARUTI.NS        0
NTPC.NS          0
POWERGRID.NS     0
RELIANCE.NS      0
SBIN.NS          0
SUNPHARMA.NS     0
TATASTEEL.NS     0
TCS.NS           0
ULTRACEMCO.NS    0
dtype: int64

In [10]:
print("Start date:", adj_close.index.min())
print("End date:", adj_close.index.max())

Start date: 2015-01-01 00:00:00
End date: 2025-12-31 00:00:00

In [11]:
adj_close.to_csv("adjusted_prices.csv")